// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service01.proto

package grpc.project.Service01;

public final class Service01Impl {
  private Service01Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service01_RequestRFIDMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service01_RequestRFIDMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service01_RequestDoorAccessMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service01_RequestDoorAccessMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service01_ResponseAccess_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service01_ResponseAccess_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service01_RequestSecProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service01_RequestSecProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service01_SecurityProfile_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service01_SecurityProfile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Service01.proto\022\tService01\"\036\n\016RequestR" +
      "FIDMsg\022\014\n\004code\030\001 \001(\t\"4\n\024RequestDoorAcces" +
      "sMsg\022\017\n\007door_id\030\001 \001(\t\022\013\n\003pin\030\002 \001(\t\")\n\016Re" +
      "sponseAccess\022\027\n\017access_response\030\001 \001(\t\"#\n" +
      "\021RequestSecProfile\022\016\n\006userId\030\001 \001(\t\"\205\001\n\017S" +
      "ecurityProfile\022\026\n\016security_level\030\001 \001(\t\022\023" +
      "\n\013secure_flag\030\002 \001(\010\022\027\n\017two_factor_auth\030\003" +
      " \001(\010\022\027\n\017employment_type\030\004 \001(\t\022\023\n\013access_" +
      "date\030\005 \001(\t2\212\002\n\026SecurityRequestService\022E\n" +
      "\013RequestRFID\022\031.Service01.RequestRFIDMsg\032" +
      "\031.Service01.ResponseAccess\"\000\022S\n\021RequestD" +
      "oorAccess\022\037.Service01.RequestDoorAccessM" +
      "sg\032\031.Service01.ResponseAccess\"\000(\001\022T\n\026Req" +
      "uestSecurityProfile\022\034.Service01.RequestS" +
      "ecProfile\032\032.Service01.SecurityProfile\"\000B" +
      ")\n\026grpc.project.Service01B\rService01Impl" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service01_RequestRFIDMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service01_RequestRFIDMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service01_RequestRFIDMsg_descriptor,
        new java.lang.String[] { "Code", });
    internal_static_Service01_RequestDoorAccessMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Service01_RequestDoorAccessMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service01_RequestDoorAccessMsg_descriptor,
        new java.lang.String[] { "DoorId", "Pin", });
    internal_static_Service01_ResponseAccess_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Service01_ResponseAccess_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service01_ResponseAccess_descriptor,
        new java.lang.String[] { "AccessResponse", });
    internal_static_Service01_RequestSecProfile_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Service01_RequestSecProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service01_RequestSecProfile_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_Service01_SecurityProfile_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Service01_SecurityProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service01_SecurityProfile_descriptor,
        new java.lang.String[] { "SecurityLevel", "SecureFlag", "TwoFactorAuth", "EmploymentType", "AccessDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
