// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Service03.proto

package grpc.project.Service03;

public final class Service03Impl {
  private Service03Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service03_BlockAccessMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service03_BlockAccessMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service03_BlockAccessResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service03_BlockAccessResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service03_SuggestIncidentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service03_SuggestIncidentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Service03_SuggestIncidentResponseMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Service03_SuggestIncidentResponseMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Service03.proto\022\tService03\":\n\022BlockAcc" +
      "essMessage\022\017\n\007user_id\030\001 \001(\t\022\023\n\013secure_fl" +
      "ag\030\002 \001(\010\",\n\032BlockAccessResponseMessage\022\016" +
      "\n\006result\030\001 \001(\t\"=\n\026SuggestIncidentRequest" +
      "\022#\n\033access_fail_condition_trips\030\001 \001(\t\">\n" +
      "\032SuggestIncidentResponseMsg\022\016\n\006key_id\030\001 " +
      "\001(\t\022\020\n\010response\030\002 \001(\t2\324\001\n\020IncidentRespon" +
      "se\022U\n\013BlockAccess\022\035.Service03.BlockAcces" +
      "sMessage\032%.Service03.BlockAccessResponse" +
      "Message\"\000\022i\n\027SuggestIncidentResponse\022!.S" +
      "ervice03.SuggestIncidentRequest\032%.Servic" +
      "e03.SuggestIncidentResponseMsg\"\000(\0010\001B)\n\026" +
      "grpc.project.Service03B\rService03ImplP\001b" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Service03_BlockAccessMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Service03_BlockAccessMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service03_BlockAccessMessage_descriptor,
        new java.lang.String[] { "UserId", "SecureFlag", });
    internal_static_Service03_BlockAccessResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Service03_BlockAccessResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service03_BlockAccessResponseMessage_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_Service03_SuggestIncidentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Service03_SuggestIncidentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service03_SuggestIncidentRequest_descriptor,
        new java.lang.String[] { "AccessFailConditionTrips", });
    internal_static_Service03_SuggestIncidentResponseMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Service03_SuggestIncidentResponseMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Service03_SuggestIncidentResponseMsg_descriptor,
        new java.lang.String[] { "KeyId", "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
